#docker-compose -f docker-compose-full.yml up -d
version: '3.7'

services:
  mysqldb:
    image: mysql:8.0.27
    container_name: mysql
    restart: always #restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    ports:
      - "3306:3306"
    expose:
      - "3306"
    networks:
      - mysql-database

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.1
    container_name: mysqladmin
    links:
      - mysqldb
    environment:
      PMA_HOST: mysqldb
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8000:80"
    networks:
      - mysql-database

  expense:
    depends_on:
      - mysqldb
    image: expense:1.0.0
    container_name: expenses
    environment:
      EXP_CONFIG_DATABASE_NAME: expense
      EXP_CONFIG_USER_NAME: root
      EXP_CONFIG_PASS_NAME: root
      EXP_CONFIG_HOST_NAME: mysqldb
    ports:
      - "9000:9000"
    expose:
      - "9000"
    networks:
      - mysql-database

networks:
  mysql-database:
    driver: bridge