#docker-compose -f docker/docker-compose-dev.yml up -d
version: '3.7'

services:
  expense_dev:
    image: expense:dev
    container_name: expenses_dev
    environment:
      EXP_CONFIG_DATABASE_NAME: expense
      EXP_CONFIG_USER_NAME: root
      EXP_CONFIG_PASS_NAME: root
      EXP_CONFIG_HOST_NAME: mysqldb
      PORT: 9001
    volumes:
      - $HOME/uzrnem/expense/public:/app/public
      - $HOME/uzrnem/expense/src:/app/src
    ports:
      - "9001:9001"
    expose:
      - "9001"
    networks:
      - docker-compose-files_mysql-database
networks:
  docker-compose-files_mysql-database:
    external: true