# docker build -t expense:dev-1.0.1 -f docker/Dockerfile.dev .
FROM node:16-alpine3.14

ENV NODE_ENV=production

# Create app directory
WORKDIR /app

COPY package.json package.json

#RUN npm install
COPY node_modules node_modules

CMD [ "node", "server.js" ]